# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2526fc1f8f41fc5b50d74df8b843278dfcd871b0d68c3d9d0dc2e6d7806168cd37e6abd70f577eadccf2a51d5ec83638ba6a7f80ffcc86e03a49ccf44ae19ffa

test:
  secret_key_base: 3fae4b881aa5f673ba5202ed9e9577ebda5aceff4c27f86001943627d0e93d1f579759005da1c0af0a4fa4be6e2c6b771c9ba25fc9df5793291396ad71b1a369

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
